version: '3.9'

networks:
  fraud_detection_network:
    driver: bridge

services:
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   environment:
  #     - ZOO_ENABLE_AUTH=yes
  #     - ZOO_SERVER_USERS=user
  #     - ZOO_SERVER_PASSWORDS=password
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - fraud_detection_network

  # kafka:
  #   image: bitnami/kafka:latest
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - fraud_detection_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    networks:
      - fraud_detection_network
    volumes:
      - ./api:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    depends_on:
      - api
    networks:
      - fraud_detection_network
    volumes:
      - ./client:/app

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fraud_detection_network