# Use an official Python runtime as a parent image
FROM python:3.9-slim
# Set the working directory
WORKDIR /app

# Copy the rest of the application code to the container
COPY . /app


# Run requirements file and install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
